version: "3.8"

services:
  respondeai_frontend:
    build: .
    container_name: respondeai_frontend
    ports:
      - "3334:3000"
    networks:
      - proxy
    restart: always
  
networks:
  proxy:
    external: true
    name: traefik_proxy
